import type { FeedPost } from "../types.js";

const hoursAgo = (h: number) =>
  new Date(Date.now() - h * 3600000).toISOString();

export const seedFeedPosts: FeedPost[] = [
  {
    id: "f1",
    platform: "instagram",
    authorId: "p1",
    authorName: "Mia Chen",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mia",
    content: "New lash set + boba run = perfect Sunday 💅🧋 #ABG #LAFitness",
    imageUrl: "https://picsum.photos/seed/mia-post1/600/600",
    likes: 4821,
    comments: 234,
    timestamp: hoursAgo(2),
    hashtags: ["ABG", "LAFitness", "boba"],
  },
  {
    id: "f2",
    platform: "tiktok",
    authorId: "p1",
    authorName: "Mia Chen",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mia",
    content: "GRWM: ABG night out edition ✨ full routine in 60 sec",
    imageUrl: "https://picsum.photos/seed/mia-post2/600/800",
    likes: 128000,
    comments: 1892,
    timestamp: hoursAgo(5),
    hashtags: ["GRWM", "ABG", "nightout"],
  },
  {
    id: "f3",
    platform: "instagram",
    authorId: "p3",
    authorName: "Ashley Nguyen",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ashley",
    content: "SF rooftop vibes 🌆 who’s pulling up this weekend?",
    imageUrl: "https://picsum.photos/seed/ash-post1/600/600",
    likes: 8934,
    comments: 412,
    timestamp: hoursAgo(1),
    hashtags: ["SF", "rooftop", "baddie"],
  },
  {
    id: "f4",
    platform: "tiktok",
    authorId: "p7",
    authorName: "Rina Okada",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rina",
    content: "Vegas pool party fit check 👙🔥",
    imageUrl: "https://picsum.photos/seed/rina-post1/600/800",
    likes: 389000,
    comments: 4521,
    timestamp: hoursAgo(3),
    hashtags: ["Vegas", "poolparty", "fitcheck"],
  },
  {
    id: "f5",
    platform: "x",
    authorId: "p3",
    authorName: "Ashley Nguyen",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ashley",
    content: "LA traffic is brutal but the baddies make it worth it 🚗💨",
    likes: 2341,
    comments: 89,
    timestamp: hoursAgo(4),
    hashtags: ["LA", "ABG"],
  },
  {
    id: "f6",
    platform: "instagram",
    authorId: "p2",
    authorName: "Jessica Park",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jessica",
    content: "Post-pilates glow + new nails 💪💅 #fitnessbaddie",
    imageUrl: "https://picsum.photos/seed/jess-post1/600/600",
    likes: 3210,
    comments: 156,
    timestamp: hoursAgo(6),
    hashtags: ["fitnessbaddie", "pilates", "nails"],
  },
  {
    id: "f7",
    platform: "tiktok",
    authorId: "p5",
    authorName: "Luna Tran",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=luna",
    content: "Houston night market food tour 🍜🔥 must try spots",
    imageUrl: "https://picsum.photos/seed/luna-post1/600/800",
    likes: 245000,
    comments: 3201,
    timestamp: hoursAgo(8),
    hashtags: ["Houston", "nightmarket", "foodie"],
  },
  {
    id: "f8",
    platform: "facebook",
    authorId: "p6",
    authorName: "Chloe Wang",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chloe",
    content: "Seattle ABG meetup this Saturday! DM me to join the group 💕",
    likes: 234,
    comments: 45,
    timestamp: hoursAgo(12),
    hashtags: ["Seattle", "ABG", "meetup"],
  },
  {
    id: "f9",
    platform: "instagram",
    authorId: "p4",
    authorName: "Sophie Kim",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie",
    content: "K-town soju night 🍶✨ tag your baddie bestie",
    imageUrl: "https://picsum.photos/seed/soph-post1/600/600",
    likes: 5678,
    comments: 289,
    timestamp: hoursAgo(7),
    hashtags: ["Ktown", "soju", "NYC"],
  },
  {
    id: "f10",
    platform: "tiktok",
    authorId: "p2",
    authorName: "Jessica Park",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jessica",
    content: "My 10-step K-beauty routine that actually works 🧴",
    imageUrl: "https://picsum.photos/seed/jess-post2/600/800",
    likes: 89000,
    comments: 1234,
    timestamp: hoursAgo(10),
    hashtags: ["Kbeauty", "skincare", "ABG"],
  },
  {
    id: "f11",
    platform: "x",
    authorId: "p7",
    authorName: "Rina Okada",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rina",
    content: "Just booked flights to Miami for spring break. ABG takeover incoming 🌴",
    likes: 8901,
    comments: 234,
    timestamp: hoursAgo(9),
    hashtags: ["Miami", "springbreak"],
  },
  {
    id: "f12",
    platform: "instagram",
    authorId: "p7",
    authorName: "Rina Okada",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rina",
    content: "Vegas lights + new fit = chef’s kiss 💋",
    imageUrl: "https://picsum.photos/seed/rina-post2/600/600",
    likes: 15234,
    comments: 678,
    timestamp: hoursAgo(0.5),
    hashtags: ["Vegas", "OOTD", "baddie"],
  },
];