import type { Profile } from "../types.js";

const avatar = (seed: string) =>
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}&backgroundColor=ffdfbf,ffd5dc,c0aede`;

const cover = (seed: string) =>
  `https://picsum.photos/seed/${seed}/800/400`;

export const seedProfiles: Profile[] = [
  {
    id: "p1",
    name: "Mia Chen",
    age: 23,
    city: "Los Angeles, CA",
    bio: "Bubble tea connoisseur ☕️ Lashes on fleek. Night market runs every weekend.",
    avatar: avatar("mia"),
    coverImage: cover("mia-cover"),
    vibes: ["baddie", "nightlife", "fashion", "foodie"],
    interests: ["lash extensions", "boba", "raves", "streetwear"],
    socials: [
      { platform: "instagram", username: "mia.chen.abg", url: "https://instagram.com/mia.chen.abg", followers: 48200 },
      { platform: "tiktok", username: "@miachen", url: "https://tiktok.com/@miachen", followers: 128000 },
      { platform: "x", username: "miachen_", url: "https://x.com/miachen_", followers: 12400 },
    ],
    abgScore: 94,
    distanceKm: 2.3,
    isOnline: true,
    lastActive: new Date().toISOString(),
    sauce: {
      platform: "tiktok",
      label: "TikTok FYP — boba girlies",
      sourceUrl: "https://tiktok.com/@miachen/video/7123456789",
      spottedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
      context: "via #abg #nightmarket",
    },
  },
  {
    id: "p2",
    name: "Jessica Park",
    age: 21,
    city: "Irvine, CA",
    bio: "UC student by day, ABG by night 💅 Gym rat + skincare obsessed",
    avatar: avatar("jessica"),
    coverImage: cover("jess-cover"),
    vibes: ["fitness", "skincare", "baddie", "study"],
    interests: ["pilates", "k-beauty", "matcha", "anime"],
    socials: [
      { platform: "instagram", username: "jesspark.abg", url: "https://instagram.com/jesspark.abg", followers: 31500 },
      { platform: "tiktok", username: "@jesspark", url: "https://tiktok.com/@jesspark", followers: 89000 },
    ],
    abgScore: 88,
    distanceKm: 8.1,
    isOnline: true,
    lastActive: new Date().toISOString(),
    sauce: {
      platform: "instagram",
      label: "Instagram Explore — pilates girlies",
      sourceUrl: "https://instagram.com/reel/jesspark.abg",
      spottedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
      context: "via #kbeauty reel",
    },
  },
  {
    id: "p3",
    name: "Ashley Nguyen",
    age: 25,
    city: "San Francisco, CA",
    bio: "Tech girlie who still knows how to party 🌃 SF → LA every other weekend",
    avatar: avatar("ashley"),
    coverImage: cover("ash-cover"),
    vibes: ["nightlife", "fashion", "travel", "baddie"],
    interests: ["clubbing", "designer bags", "pho", "photography"],
    socials: [
      { platform: "instagram", username: "ash.nguyen", url: "https://instagram.com/ash.nguyen", followers: 67800 },
      { platform: "facebook", username: "ashley.nguyen", url: "https://facebook.com/ashley.nguyen", followers: 4200 },
      { platform: "x", username: "ashnguyen", url: "https://x.com/ashnguyen", followers: 8900 },
      { platform: "tiktok", username: "@ashnguyen", url: "https://tiktok.com/@ashnguyen", followers: 201000 },
    ],
    abgScore: 96,
    distanceKm: 15.4,
    isOnline: false,
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    sauce: {
      platform: "x",
      label: "X timeline — SF nightlife thread",
      sourceUrl: "https://x.com/ashnguyen/status/1789012345678901234",
      spottedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
      context: "quoted in ABG night-out post",
    },
  },
  {
    id: "p4",
    name: "Sophie Kim",
    age: 22,
    city: "New York, NY",
    bio: "K-town regular 🍜 Lashes, nails, and good vibes only",
    avatar: avatar("sophie"),
    coverImage: cover("soph-cover"),
    vibes: ["foodie", "baddie", "fashion", "beauty"],
    interests: ["korean BBQ", "nail art", "soju nights", "thrifting"],
    socials: [
      { platform: "instagram", username: "sophie.kim.nyc", url: "https://instagram.com/sophie.kim.nyc", followers: 54300 },
      { platform: "tiktok", username: "@sophiekim", url: "https://tiktok.com/@sophiekim", followers: 156000 },
    ],
    abgScore: 91,
    distanceKm: 45.2,
    isOnline: true,
    lastActive: new Date().toISOString(),
    sauce: {
      platform: "tiktok",
      label: "TikTok search — K-town nails",
      sourceUrl: "https://tiktok.com/@sophiekim/video/7234567890",
      spottedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
      context: "via #ktown #nails",
    },
  },
  {
    id: "p5",
    name: "Luna Tran",
    age: 24,
    city: "Houston, TX",
    bio: "Vietnamese baddie 🇻🇳 Houston heat matches my energy",
    avatar: avatar("luna"),
    coverImage: cover("luna-cover"),
    vibes: ["baddie", "fitness", "travel", "music"],
    interests: ["EDM", "tattoos", "banh mi", "yoga"],
    socials: [
      { platform: "instagram", username: "luna.tran.htx", url: "https://instagram.com/luna.tran.htx", followers: 38900 },
      { platform: "tiktok", username: "@lunatran", url: "https://tiktok.com/@lunatran", followers: 245000 },
      { platform: "x", username: "lunatran_", url: "https://x.com/lunatran_", followers: 6700 },
    ],
    abgScore: 89,
    distanceKm: 32.7,
    isOnline: false,
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    sauce: {
      platform: "instagram",
      label: "Instagram suggested — Houston baddies",
      sourceUrl: "https://instagram.com/p/lunatran.htx",
      spottedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
      context: "mutual follow graph",
    },
  },
  {
    id: "p6",
    name: "Chloe Wang",
    age: 20,
    city: "Seattle, WA",
    bio: "PNW princess with LA baddie energy ✨ Coffee + couture",
    avatar: avatar("chloe"),
    coverImage: cover("chloe-cover"),
    vibes: ["fashion", "study", "foodie", "beauty"],
    interests: ["vintage shopping", "latte art", "C-dramas", "hiking"],
    socials: [
      { platform: "instagram", username: "chloewang.abg", url: "https://instagram.com/chloewang.abg", followers: 22100 },
      { platform: "facebook", username: "chloe.wang", url: "https://facebook.com/chloe.wang", followers: 1800 },
    ],
    abgScore: 82,
    distanceKm: 28.9,
    isOnline: true,
    lastActive: new Date().toISOString(),
    sauce: {
      platform: "facebook",
      label: "Facebook group — PNW Asian creatives",
      sourceUrl: "https://facebook.com/groups/pnwabg/posts/123456",
      spottedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
      context: "shared in outfit check thread",
    },
  },
  {
    id: "p7",
    name: "Rina Okada",
    age: 26,
    city: "Las Vegas, NV",
    bio: "Vegas baby 🎰 Pool parties, bottle service, and bottomless brunch",
    avatar: avatar("rina"),
    coverImage: cover("rina-cover"),
    vibes: ["nightlife", "baddie", "travel", "fashion"],
    interests: ["dayclubs", "luxury cars", "sushi", "DJ sets"],
    socials: [
      { platform: "instagram", username: "rina.okada", url: "https://instagram.com/rina.okada", followers: 112000 },
      { platform: "tiktok", username: "@rinaokada", url: "https://tiktok.com/@rinaokada", followers: 389000 },
      { platform: "x", username: "rinaokada", url: "https://x.com/rinaokada", followers: 34500 },
      { platform: "facebook", username: "rina.okada", url: "https://facebook.com/rina.okada", followers: 8900 },
    ],
    abgScore: 98,
    distanceKm: 55.0,
    isOnline: true,
    lastActive: new Date().toISOString(),
    sauce: {
      platform: "tiktok",
      label: "TikTok FYP — Vegas pool party",
      sourceUrl: "https://tiktok.com/@rinaokada/video/7345678901",
      spottedAt: new Date(Date.now() - 30 * 60000).toISOString(),
      context: "via #vegas #dayclub",
    },
  },
  {
    id: "p8",
    name: "Emily Liu",
    age: 23,
    city: "Boston, MA",
    bio: "East coast ABG 🦞 Harvard adjacent, baddie certified",
    avatar: avatar("emily"),
    coverImage: cover("emily-cover"),
    vibes: ["study", "baddie", "fitness", "foodie"],
    interests: ["med school prep", "hot pot", "running", "K-pop"],
    socials: [
      { platform: "instagram", username: "emilyliu.abg", url: "https://instagram.com/emilyliu.abg", followers: 28700 },
      { platform: "tiktok", username: "@emilyliu", url: "https://tiktok.com/@emilyliu", followers: 67000 },
    ],
    abgScore: 85,
    distanceKm: 62.1,
    isOnline: false,
    lastActive: new Date(Date.now() - 86400000).toISOString(),
    sauce: {
      platform: "instagram",
      label: "Instagram Reels — East Coast study baddies",
      sourceUrl: "https://instagram.com/reel/emilyliu.abg",
      spottedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      context: "via #harvardadjacent",
    },
  },
];